name: Deploy CDK Code

on:
  push:
    branches:
      - feat/TRN-1-use-vpc-construct

jobs:
  deploy-manifests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Synthesize Kubernetes CDK Code
        run: |
          cd ./kubernetes
          yarn install --frozen-lockfile
          yarn cdk8s synth

      - name: Checkout Destination Repo
        uses: actions/checkout@v4
        with:
          repository: 'dromix/cicd'
          ssh-key: ${{ secrets.DESTINATION_REPO_SSH_KEY }}
          path: 'destination-repo'

      - name: Move Kubernetes CDK Code
        run: |
          cp -r kubernetes/dist/* destination-repo/kubernetes/

      - name: Commit Changes
        run: |
          cd destination-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update Kubernetes CDK code"
          git push
