name: Deploy CDK Code

on:
  push:
    branches:
      - feat/TRN-1-use-vpc-construct

jobs:
  deploy-manifests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Synthesize Kubernetes CDK Code
        run: |
          cd ./kubernetes
          yarn install --frozen-lockfile
          yarn cdk8s synth

      - name: Add SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DESTINATION_REPO_SSH_KEY }}
        run: |
          eval "$(ssh-agent -s)"
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        shell: bash

      - name: Clone Destination Repo
        run: |
          git clone git@github.com:dromix/cicd.git destination-repo

      - name: Move Kubernetes CDK Code
        run: |
          cp -r kubernetes/dist/* destination-repo/kubernetes/
        working-directory: ./destination-repo

      - name: Set Commit Name
        run: |
          cd destination-repo
          git add .
          git commit -m "${{ steps.commit.outputs.commit }}"
        working-directory: ./destination-repo

