name: Deploy CDK Code

on:
  push:
    branches:
      - feat/TRN-1-use-vpc-construct

jobs:
  deploy-manifests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Synthesize Kubernetes CDK Code
        run: |
          cd ./kubernetes
          yarn install --frozen-lockfile
          yarn cdk8s synth

      - name: Get Committer Info from Source Repo
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
          echo "COMMITTER_NAME=$(git log -1 --pretty=format:'%cn')" >> $GITHUB_ENV
          echo "COMMITTER_EMAIL=$(git log -1 --pretty=format:'%ce')" >> $GITHUB_ENV
        
      - name: Checkout Destination Repo
        uses: actions/checkout@v4
        with:
          repository: 'dromix/cicd'
          ssh-key: ${{ secrets.DESTINATION_REPO_SSH_KEY }}
          path: 'destination-repo'

      - name: Create Kubernetes Directory in Destination Repo
        run: |
          mkdir -p destination-repo/kubernetes/

      - name: Move Kubernetes CDK Code
        run: |
          cp -rf kubernetes/dist/* destination-repo/kubernetes/

      - name: Commit Changes
        run: |
          cd destination-repo
          git config user.name "$COMMITTER_NAME"
          git config user.email "$COMMITTER_EMAIL"
          git add .

          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "$COMMIT_MESSAGE"
            git push
          fi
